apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    # Only scrape pods that have the annotation "prometheus.io/scrape=true"
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    
    # Get the scrape path from annotation or default to /metrics
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    
    # Get the scrape port from annotation or default to the pod's container port
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    
    # Add standard Kubernetes labels to the metrics
    - source_labels: [__meta_kubernetes_namespace]
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      target_label: kubernetes_pod_name
    - source_labels: [__meta_kubernetes_pod_container_name]
      target_label: kubernetes_container_name
    - source_labels: [__meta_kubernetes_pod_phase]
      regex: (Failed|Succeeded)
      action: drop
    
    # Optional: Add any custom labels from pod annotations
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_custom_label]
      target_label: custom_label
      regex: (.+)